### ISSUE TITLE
Envoy proxy does not generate B3 Trace headers for api calls to different service

### ISSUE THREAD

**Issue by SubhadeepSen** [krakendio/krakend-ce#493]
Hi 

I have installed krakend in my kubernetes cluster. The cluster has istio installed too and istio tracing feature is also enabled. When I'm invoking krakend gateway for some endpoint, I see there is no INBOUND request in envoy proxy logs (sidecar running along with krakend pod). Moreover, I do not see the B3 Trace Context headers which are by default added by envoy proxy when krakend gateway is not used. I see the B3 Trace Context headers only when krakend **_/debug_** endpoint is invoked. I'm not sure if I am missing any configuration.

Q. Does krakend bypass the envoy proxy for api calls to a different service ?

I really appreciate on any suggestions or guidance.

```json
{
    "version": 2,
    "name": "KrakenD on k8s",
    "port": 8080,
    "cache_ttl": "3600s",
    "timeout": "10s",
    "endpoints": [{
            "endpoint": "/debug",
            "backend": [{
                    "host": ["http://krakend-service:8000"],
                    "url_pattern": "/__debug/debug"
                }
            ]
        },
		{
            "endpoint": "/randomNumber",
            "backend": [{
                    "host": ["http://number-generator-app:8080"],
                    "url_pattern": "/randomNumber"
                }
            ]
        }
    ]
}
```

1. B3 Trace Context Headers (Envoy) are logged for the 1st endpoint in the sidecar running along with krakend pod
2. B3 Trace Context Headers (Envoy) are **_NOT_** logged for the 2nd endpoint in the sidecar running along with krakend pod

Thanks !

**Comment by kpacha** [comment]
KrakenD drops all headers by default, so if you want to propagate them you need to add the `input_header` property to your endpoint definition (https://www.krakend.io/docs/endpoints/parameter-forwarding/)

On the other hand, since you are already tracing your environment using B3 trace contexts, you could enable the opencensus component and start adding traces from krakend into your telemetry stack (https://www.krakend.io/docs/telemetry/opencensus/)
