### ISSUE TITLE
Krakend not reaching to second host when fist host fails in the call

### ISSUE THREAD

**Issue by krishna-kunderu** [krakendio/krakend-ce#551]
Hello @alombarte , @kpacha 
Krakend 2.0.5

endpoint configuration
```
{
    "endpoint": "api/{route}/{id}",
    "timeout": "6s",
    "method": "GET",
    "backend": [
        {
          "url_pattern": "/{route}/{id}",
          "method": "GET",
          "host": [
              "http://{{.envConfig.loadBalancerIP}}:{{.envConfig.apiPort}}",
              "http://{{.envConfig.drloadBalancerIP}}:{{.envConfig.apiPort}}"
          ]          
        }
    ]
}

```

So when loadBalancerIP is down in the above hosts giving error after in about 3 seconds and not calling onto the second host which live.

The first host is giving this error
`"http://unknownhost:5001/route/136": dial tcp: lookup unknownhost on XX.XX.X.XX:XX: no answer from DNS server`

I would expect it calls the other host and gets the response. I am getting sometimes response and sometime about error where unknownhost is the 1st in the list of hosts.

I followed the documentation to setup the above route.

**Comment by kpacha** [comment]
by design, KrakenD does not retry when an error happens.

on the other hand, since you are using a static service discovery, KrakenD is just picking a host from the list in a round robin fashion, and sending the next request to it (that's why sometime you are seeing the flacky behavior).

if you want this process of service discovery to be handled automatically, you'll need to use the DNS service discovery as described here: https://www.krakend.io/docs/backends/service-discovery/#dns-srv-service-discovery-kubernetesconsul

cheers!

**Comment by krishna-kunderu** [comment]
@kpacha Thanks very much for your quick response. This is very helpful
