### ISSUE TITLE
Upload file - Timeout

### ISSUE THREAD

**Issue by elvince** [krakendio/krakend-ce#598]
**Describe what are you trying to do**:
Upload a max 10Mo files via the gateway.

**Your configuration file**:
```json
{
  "version": 3,
"timeout":"30s"
  ...
{"endpoint":"/v1/upload","input_headers":["*"],"input_query_strings":[],"method":"Post","output_encoding":"no-op","extra_config":{}
}
```
**Additional comments:**
How can I manage to only set the pipe timeout per EndPoint?
I have no need to set the timeout to 30sec for 95% of my end points.
The only timeout I found at the endpoint level is a "Backend Time out" not a pipe one.
As it is an upload, I can't manage to tweak my endpoint timeout value.

Thanks,

**Comment by alombarte** [comment]
Hi @elvince ,

See this: https://www.krakend.io/docs/throttling/timeouts/#endpoint-specific-timeout

**Comment by alombarte** [comment]
Hi @elvince,

The timeout kind of works the other way around. The one at the root level is only used when there is no `timeout` entry in the endpoint, it's a default and not a global value.

You might need to double-check that your configuration is correct (make a `krakend check -t -c krakend.json --lint`) and provide the full configuration and logs rather than a description (the one you passed is not correct). When you say that KrakenD is dropping the connection, are you seeing a `context deadline exceeded` in the logs?

The following configuration works fine (I just tested it on KrakenD 2.1):
```
{
  "$schema": "https://www.krakend.io/schema/v3.json",
  "version": 3,
  "timeout": "30s",
  "endpoints": [
    {
      "endpoint": "/v1/upload",
      "method": "POST",
      "output_encoding": "no-op",
      "input_query_strings": ["*"],
      "timeout": "2s",
      "backend": [
        {
          "url_pattern": "/",
          "host": ["http://php:8081"]
        }
      ]
    }
  ]
}
```
The backend that is consuming has a timeout of 3 seconds. I can see how KrakenD cuts at 2 (`context deadline exceeded`) while dealing with it (and not 30s). Increasing the endpoint timeout works just fine.

In addition to the endpoint timeout, you also have
- https://www.krakend.io/docs/service-settings/http-transport-settings/
- https://www.krakend.io/docs/service-settings/http-server-settings/

**Comment by elvince** [comment]
hi @alombarte 
Thanks for you answers.

Yes I'm seeing "context deadline exceeded" in the logs.
the timeout at root level is a full range timeout, in the doc they call it "user full pipe", where as the endpoint timeout is only link to the backend timeout. May be I miss understand the docs. Why they make the difference between full pipe timeout and backend timeout?

In case of an upload file, it is not the time to process the backend that is wrong (just a few second) but the time to upload the file.

The first test I did was to set the root timeout at 2sec and the endpoint one at 30s. My upload was cut at 2 sec. I will make other test and keep you updated.

FYI, my config is correct and checked, I just remove stuff for readability.

Thanks for your time you took to answer me.

**Comment by alombarte** [comment]
I wrote that piece of documentation, and I am happy to improve it if it's unclear. I'll try to clarify:

- There is no difference between the endpoint timeout, and the one at the root. The one at the root is a default value for those endpoints not declaring a timeout, so KrakenD can have somewhere to get a value when evaluating an individual endpoint.
- The endpoint timeout IS NOT linked to the backend, but the full pipe. In your case  you are connecting to 1 backend because it's a write operation, but you could have 100 backends connected to one endpoint, and the timeout is for the whole pipe of all, including the time your middlewares and plugins spend doing stuff.
- There is no way the root timeout is going to override the endpoint timeout, as explained above. It must be a miss-configuration.

Make additional tests (including the two links that I passed) and keep me in the loop. 

I am happy to assist, you are welcome

**Comment by elvince** [comment]
@alombarte 

Thanks for the time you spent on this ticket.

On my latest test, everything is working as expected.

I think what confused me in the documentation is that:

- In the Timeout Doc you used "whole duration of the pipe (and not only the connection to the backends)"
- In the Endpoint doc you used "Maximum time you’ll wait for the slowest backend response"

I think the endpoint doc is wrong following your last message. You might fix it.

Thanks,
