### ISSUE TITLE
Upload / Download large files via krakend

### ISSUE THREAD

**Issue by siva-nexturn** [krakendio/krakend-ce#708]
krakend seems to have a huge performance overhead when uploading / downloading files via REST endpoints - 25x slower than transferring files without krakend! The gateway has been configured to proxy directly to the backend with no-op to ensure there are no operations on the data.

We are considering using krakend for its Authentication and Authorization capabilities, however this performance issue is a big dampener and have to look for alternatives if there is no resolution.

**Comment by alombarte** [comment]
Hi @siva-nexturn,

The problem is probably related to the network, the hardware specs of the pieces you are comparing (backend vs KrakenD), the method to upload files, or many other variables. What I am supposed to do with this information? How do I reproduce this doom scenario you are describing? The issue you have opened is not actionable on our side.

File upload is quite frequent in KrakenD, and although you are adding a piece in the middle, and the information as an extra hop, the numbers you are reflecting do not represent the reality of any KrakenD users we've seen so far.

**Comment by siva-nexturn** [comment]
Thank you @alombarte. Its reassuring to know that file uploads/download scenarios are pretty common in krakend. These tests were done on a simple desktop configuration with docker container setup. Will perform these tests on more realistic (i.e. prod like) environment to better compare.

**Comment by kpacha** [comment]
I think there is one important point to keep in mind: requests and responses are not streamed. krakend must read the request body before passing it to the backend
